#!/usr/bin/env bash
# Epic: security_and_cross_cutting_master
# Lifecycle: permanent
# Delete-when: NA
# load-gh-token.sh — export a WORKFLOW-CAPABLE GH_TOKEN for gh + git in EVERY context.
#
# Why this exists (codified 2026-06-01): the gh CLI keyring login token (`gho_…`) carries
# scopes `repo, read:org, gist, admin:public_key` — it has **NO `workflow` scope**, so any
# gh-API / HTTPS push that creates or updates `.github/workflows/*.yml` is silently refused
# ("refusing to allow … without `workflow` scope"). That blocked a 7-repo CI v1→v2 migration.
# The `GH_PAT` secret (Secret Manager / AWS SM) IS workflow-capable (fine-grained PAT with
# "Workflows: read/write"). This helper makes that PAT the active GH_TOKEN so gh + git never
# stop on a permission gap — on slots, the main worktree, and orchestrator VM workers alike.
#
# Usage (idempotent; safe to source repeatedly):
#   source unified-trading-pm/scripts/workspace/load-gh-token.sh
# After sourcing, GH_TOKEN + GITHUB_TOKEN are exported (env beats the keyring for both gh + git).
#
# SSH note: git push over SSH (a user key) is NOT subject to the workflow-scope restriction, so
# ssh-protocol slots can already push workflow files. This helper covers the gh-API / HTTPS path
# (gh workflow run, gh api contents PUT, https clones/pushes) which IS restricted.

_uts_load_gh_token() {
  # Respect an already-exported workflow-capable token.
  if [ -n "${GH_TOKEN:-}" ]; then
    [ -z "${GITHUB_TOKEN:-}" ] && export GITHUB_TOKEN="${GH_TOKEN}"
    return 0
  fi

  local _pat=""

  # 1) PREFERRED: local .act-secrets (workspace root). Generated by
  #    scripts/workspace/generate-act-secrets.sh, holds `GH_PAT=<token>` with repo+workflow
  #    scope (it's the same token act uses for ci-status-update dispatch). Fast + offline.
  #    Check the slot WORKSPACE_ROOT, its parent (slots live under <repos-root>/.tabs/<N>/),
  #    REPO_ROOT, and HOME — mirrors the .act-secrets discovery in quality-gates-base/.
  local _cand
  for _cand in "${WORKSPACE_ROOT:-}/.act-secrets" "${WORKSPACE_ROOT:-}/../.act-secrets" \
               "${WORKSPACE_ROOT:-}/../../.act-secrets" "${REPO_ROOT:-}/.act-secrets" \
               "${HOME}/.act-secrets" "${HOME}/.secrets"; do
    [ -n "${_cand}" ] && [ -f "${_cand}" ] || continue
    _pat="$(grep -E '^GH_PAT=' "${_cand}" 2>/dev/null | head -1 | cut -d= -f2- | tr -d '"'"'"' ')"
    [ -n "${_pat}" ] && { echo "[load-gh-token] GH_TOKEN from ${_cand}" >&2; break; }
  done

  # 1b) VALIDATE the cached token (codified 2026-06-01): a `.act-secrets` GH_PAT can
  #     EXPIRE / be rotated, and the old design used it blindly — exporting a dead token
  #     so every gh-API/HTTPS call 401s mid-task while `git push` still works (SSH remote),
  #     making the breakage silent + confusing. One cheap probe to /rate_limit (free, works
  #     for any valid token incl fine-grained; never counts against quota) discriminates
  #     200=valid vs 401=dead. On a dead cached token, clear it so path 2 (Secret Manager,
  #     authoritative) takes over. --max-time bounds shell-init latency; skip the probe only
  #     if curl is absent (offline) — then we trust the cache as before.
  if [ -n "${_pat}" ] && command -v curl >/dev/null 2>&1; then
    local _probe
    _probe="$(curl -s -o /dev/null -w '%{http_code}' --max-time 6 \
      -H "Authorization: token ${_pat}" -H "Accept: application/vnd.github+json" \
      "https://api.github.com/rate_limit" 2>/dev/null)"
    if [ "${_probe}" != "200" ]; then
      echo "WARN [load-gh-token] cached .act-secrets GH_PAT failed validity probe (HTTP ${_probe}) —" >&2
      echo "     it is likely expired/rotated; falling through to Secret Manager." >&2
      _pat=""
    fi
  fi

  # 2) FALLBACK: Secret Manager — GCP (asia/central project), then AWS (fleet).
  if [ -z "${_pat}" ] && command -v gcloud >/dev/null 2>&1; then
    _pat="$(gcloud secrets versions access latest --secret=GH_PAT \
      --project="${GCP_PROJECT_ID:-central-element-323112}" 2>/dev/null || true)"
  fi
  if [ -z "${_pat}" ] && command -v aws >/dev/null 2>&1; then
    _pat="$(aws secretsmanager get-secret-value --secret-id GH_PAT \
      --query SecretString --output text 2>/dev/null || true)"
  fi

  if [ -n "${_pat}" ]; then
    export GH_TOKEN="${_pat}"
    export GITHUB_TOKEN="${_pat}"
    unset _pat
    return 0
  fi

  echo "WARN [load-gh-token] GH_PAT unavailable from GCP/AWS Secret Manager — gh/git will fall" >&2
  echo "     back to the keyring login token, which LACKS 'workflow' scope. Workflow-file edits" >&2
  echo "     via gh-API/HTTPS will be refused. Fix: grant SM access OR set GH_TOKEN manually." >&2
  return 1
}

_uts_load_gh_token

# Optional self-check: confirm the active token can write workflows (non-mutating probe).
# Enable with UTS_GH_TOKEN_VERIFY=1 (skipped by default to keep shell init fast).
if [ "${UTS_GH_TOKEN_VERIFY:-0}" = "1" ] && [ -n "${GH_TOKEN:-}" ]; then
  _code="$(curl -s -o /dev/null -w '%{http_code}' -X PUT \
    -H "Authorization: token ${GH_TOKEN}" -H "Accept: application/vnd.github+json" \
    "https://api.github.com/repos/IggyIkenna/unified-trading-pm/contents/.github/workflows/quality-gates-v2.yml" \
    -d '{"message":"probe","content":"eA==","sha":"0000000000000000000000000000000000000000","branch":"live-defi-rollout"}' 2>/dev/null)"
  # 409/422 = permission OK (failed only at the bogus sha); 403 = missing Workflows:write.
  case "${_code}" in
    409|422) echo "[load-gh-token] GH_TOKEN is workflow-capable ✓" >&2 ;;
    403)     echo "[load-gh-token] ⚠️  GH_TOKEN LACKS Workflows:write (HTTP 403) — workflow edits will block" >&2 ;;
    *)       echo "[load-gh-token] workflow-capability probe inconclusive (HTTP ${_code})" >&2 ;;
  esac
  unset _code
fi
