#!/usr/bin/env python3
# Epic: ci_master
# Lifecycle: permanent
# Delete-when: NA
"""Project the Firestore ci_status aggregate -> workspace-manifest.json (one commit/interval).

Phase-3 consolidator (GHA hourly cron, ci-status-consolidator.yml — WS-A). Firestore is the
live SSOT for ci_status (written by ci-status-update.yml's set_status CAS, one doc per repo).
This job periodically projects ``get_all()`` into ``repositories.*.ci_status`` (+
``codebase_health``) so the manifest stays a FRESH OFFLINE-FALLBACK CACHE (quickmerge /
deployment-api read the manifest copy when Firestore is unavailable) WITHOUT the
per-transition ``[skip ci]`` commit that ``ci-status-update.yml`` makes on every CI transition
(the dominant PM-LDR commit-noise / manifest-race class — D2 / D11).

Firestore already holds the RESOLVED status (the set_status CAS applied the no-downgrade
rank semantics), so this is a dumb projection — it copies the stored value verbatim, it does
NOT re-run resolve_status. It writes the manifest ONLY when a projected VALUE actually changed
(a value-diff, never a reformat), so a no-op run produces no commit and no churn. The DAG SVG
is a gitignored regen artifact (regenerated by consumers) so it is not touched here.

CLI:
    python3 scripts/cicd/ci_status_consolidator.py
        [--manifest workspace-manifest.json] [--project-id <id>] [--dry-run]
    Always exits 0 on a clean projection (idempotent); prints CHANGED lines + a summary.
    Exits 0 + "Firestore EMPTY — skipping" when the aggregate is empty (manifest untouched —
    never blanks the cache from a transient Firestore read failure).
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import cast

# ci_status_store.py is in the same directory; add it to the path for direct-script invocation.
sys.path.insert(0, str(Path(__file__).parent))
from ci_status_store import get_all

ManifestDict = dict[str, object]
FsAggregate = dict[str, dict[str, object]]


def project(manifest: ManifestDict, fs: FsAggregate) -> list[tuple[str, str, object, object]]:
    """Mutate ``repositories.*.ci_status`` / ``codebase_health`` from the Firestore aggregate.

    Returns the list of ``(repo, field, old, new)`` changes applied (empty = no-op). A repo
    absent from Firestore is left untouched (the manifest keeps its last-known value — never
    blanked). Only a present, non-empty Firestore value that DIFFERS is projected.
    """
    repos_obj = manifest.get("repositories")
    if not isinstance(repos_obj, dict):
        return []
    repos = cast("dict[str, object]", repos_obj)
    changes: list[tuple[str, str, object, object]] = []
    for repo, meta_obj in repos.items():
        if not isinstance(meta_obj, dict):
            continue
        meta = cast("dict[str, object]", meta_obj)
        doc = fs.get(repo)
        if not doc:
            continue
        status = doc.get("status")
        if isinstance(status, str) and status and meta.get("ci_status") != status:
            changes.append((repo, "ci_status", meta.get("ci_status"), status))
            meta["ci_status"] = status
        # Recovery hygiene: ci_failure_reason is a manifest-only legacy field the green path
        # never cleared, so a recovered repo (Firestore status != FAILING) kept a stale red
        # reason — the dashboard then showed a failure reason on a healthy repo (alerting-service
        # 2026-06-26). Whenever Firestore reports a non-FAILING status, blank the stale reason
        # (codebase_health.qg_red_reason already self-heals via the blob sync below).
        if isinstance(status, str) and status and status != "FAILING" and meta.get("ci_failure_reason"):
            changes.append((repo, "ci_failure_reason", meta.get("ci_failure_reason"), None))
            meta["ci_failure_reason"] = None
        health = doc.get("codebase_health")
        if isinstance(health, dict) and meta.get("codebase_health") != health:
            changes.append((repo, "codebase_health", "<blob>", "<blob>"))
            meta["codebase_health"] = health
    return changes


def main() -> int:
    parser = argparse.ArgumentParser(description="Project Firestore ci_status -> workspace-manifest.json.")
    parser.add_argument("--manifest", default="workspace-manifest.json", help="Manifest path")
    parser.add_argument("--project-id", default=None, help="GCP project id (default: ADC / env)")
    parser.add_argument("--dry-run", action="store_true", help="Report changes without writing")
    args = parser.parse_args()

    path = Path(cast("str", args.manifest))
    manifest = cast("ManifestDict", json.loads(path.read_text(encoding="utf-8")))

    fs = cast("FsAggregate", get_all(project_id=cast("str | None", args.project_id)))
    if not fs:
        print("ci-status-consolidator: Firestore aggregate EMPTY — skipping (manifest untouched).")
        return 0

    changes = project(manifest, fs)
    if not changes:
        print(f"ci-status-consolidator: no changes ({len(fs)} Firestore docs projected; manifest already current).")
        return 0

    for repo, field, old, new in changes:
        print(f"  CHANGED {repo}.{field}: {old} -> {new}")

    if cast("bool", args.dry_run):
        print(f"ci-status-consolidator: DRY-RUN — {len(changes)} change(s) NOT written.")
        return 0

    # CANONICAL manifest form (ensure_ascii=False + indent=2 + trailing "\n") — the form
    # every other writer (update-repo-version / staging-to-main / sit-unlock / merge-driver)
    # emits, guarded by scripts/quality_gates/check_workspace_manifest_canonical.py.
    # NOT prettier: this list used to name prettier and that was FALSE — prettier collapses
    # short arrays (printWidth=120) where canonical always explodes them, so it can never emit
    # this form. It reformatted the manifest on every local commit that staged it (the
    # prettier-autostage hook matches `json`) until `workspace-manifest.json` was added to
    # .prettierignore on 2026-07-17. See that file's entry for the measured incident.
    # The previous ascii-escaped no-newline form oscillated against those writers → an
    # hourly cosmetic-churn commit loop (root-caused 2026-07-02, cicd_mvp local↔CI parity).
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(manifest, fh, indent=2, ensure_ascii=False)
        fh.write("\n")
    print(f"ci-status-consolidator: wrote {len(changes)} change(s) to {path}.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
