#!/usr/bin/env bash
# Epic: ci_master
# Lifecycle: permanent
# Delete-when: NA
#
# Register the runner-local git merge drivers + attributes that let a `git pull --rebase` over the
# manifest-mutating files auto-resolve the deterministic conflict classes instead of dying FATAL.
# Source/run this BEFORE the rebase-retry push loop in update-repo-version.yml,
# reconcile-staging-versions.yml and staging-to-main.yml.
#
# Resolves:
#   workspace-manifest.json              -> manifestmerge (semantic 3-way JSON: max-semver per
#                                           version key, union breaking_pending, recurse dicts)
#   pyproject.toml                       -> semvermax (higher `version =` wins)
#   uv.lock                              -> keepours (no-op; caller re-runs `uv lock` to reconcile)
#   plans/audit/manifest-mutations.jsonl -> union (built-in; append-only audit log)
#
# Drivers are runner-local (`git config` + `.git/info/attributes`); the committed `.gitattributes`
# carries only the `merge=` ATTRIBUTE mapping (harmless for devs without the driver configured —
# git falls back to the default text merge, exactly today's behaviour). The jsonl `merge=union`
# works for everyone (union is a git built-in) — committed in `.gitattributes`.
#
# Usage: bash scripts/cicd/setup_manifest_merge_drivers.sh [REPO_ROOT]
set -uo pipefail

_root="${1:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}"
_script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$_root" || { echo "setup_manifest_merge_drivers: cannot cd $_root" >&2; exit 1; }

git config merge.manifestmerge.name "semantic workspace-manifest.json 3-way merge"
git config merge.manifestmerge.driver "python3 ${_script_dir}/manifest_merge_driver.py %O %A %B"

git config merge.semvermax.name "semver-max version-line resolver"
git config merge.semvermax.driver "python3 ${_script_dir}/semver_max_merge_driver.py %O %A %B"

# keepours: take OUR side verbatim (exit 0, no conflict). uv.lock is regenerated by `uv lock` after
# the rebase reconciles pyproject.toml, so a literal lock conflict is noise we resolve deterministically.
git config merge.keepours.name "keep ours (uv.lock regenerated post-rebase)"
git config merge.keepours.driver "true"

# Runner-local attributes for the custom drivers (the committed .gitattributes also lists these so
# the mapping is discoverable; .git/info/attributes guarantees it even if .gitattributes lags).
mkdir -p .git/info
{
  echo "workspace-manifest.json merge=manifestmerge"
  echo "pyproject.toml merge=semvermax"
  echo "uv.lock merge=keepours"
  echo "plans/audit/manifest-mutations.jsonl merge=union"
} > .git/info/attributes

echo "setup_manifest_merge_drivers: drivers registered (manifestmerge, semvermax, keepours, union)"
