#!/usr/bin/env python3.13
# Epic: security_and_cross_cutting_master
# Lifecycle: permanent
# Delete-when: NA
"""Generate DATA_FLOW_DAG.svg from data-flow-manifest.json.

SSOT: unified-trading-pm/data-flow-manifest.json
Output: unified-trading-pm/DATA_FLOW_DAG.svg

Maps: Service domain data → API consuming that data → UI rendering that data.
Covers both batch and live modes.
"""

from __future__ import annotations

import json
import xml.etree.ElementTree as ET
from html import escape as html_escape
from pathlib import Path
from typing import Any, cast

SCRIPT_DIR = Path(__file__).parent
PM_ROOT = SCRIPT_DIR.parent.parent
MANIFEST = PM_ROOT / "data-flow-manifest.json"
OUTPUT = PM_ROOT / "DATA_FLOW_DAG.svg"

# --- Layout constants ---

BOX_H = 36
BOX_PAD = 12
ROW_H = BOX_H + 16
SECTION_HDR = 32
ARROW_W = 40
SVG_W = 1400
CHARS_PX = 7
BOX_MIN_W = 100

CSS = """
      .bg { fill: #fafbfc; }
      .title { font: 700 22px Arial, sans-serif; fill: #0f172a; }
      .subtitle { font: 500 12px Arial, sans-serif; fill: #475569; }
      .section { font: 700 14px Arial, sans-serif; fill: #0f172a; }
      .mode-batch { fill: #0ea5e9; }
      .mode-live { fill: #22c55e; }
      .label { font: 600 11px Arial, sans-serif; fill: #0f172a; }
      .small { font: 500 10px Arial, sans-serif; fill: #64748b; }
      .svc { fill: #fce7f3; stroke: #db2777; stroke-width: 1.2; rx: 6; }
      .api { fill: #f3e8ff; stroke: #7c3aed; stroke-width: 1.2; rx: 6; }
      .ui-box { fill: #ecfeff; stroke: #06b6d4; stroke-width: 1.2; rx: 6; }
      .flow-bg { fill: #ffffff; stroke: #e2e8f0; stroke-width: 1; rx: 8; }
      .arrow { fill: none; stroke: #94a3b8; stroke-width: 2; marker-end: url(#arrowhead); }
"""


def box_width(name: str) -> int:
    return max(len(name) * CHARS_PX + 20, BOX_MIN_W)


def _jdict(val: object) -> dict[str, Any] | None:
    if isinstance(val, dict):
        return cast(dict[str, Any], val)
    return None


def _jlist(val: object) -> list[object] | None:
    if isinstance(val, list):
        return cast(list[object], val)
    return None


def _jstr(val: object, default: str = "") -> str:
    return str(val) if val is not None else default


def parse_flows(data: dict[str, Any]) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    """Split flows into batch and live."""
    flows_raw = _jlist(data.get("data_flows"))
    if not flows_raw:
        return [], []

    batch: list[dict[str, Any]] = []
    live: list[dict[str, Any]] = []
    for f in flows_raw:
        entry = _jdict(f)
        if not entry:
            continue
        mode = _jstr(entry.get("mode"), "").lower()
        if mode == "batch":  # noqa: L2-mode-seam
            batch.append(entry)
        elif mode == "live":  # noqa: L2-mode-seam
            live.append(entry)

    return batch, live


def flow_nodes(flow: dict[str, object]) -> list[tuple[str, str]]:
    """Return list of (name, css_class) for Service, API, UI. API may be omitted."""
    nodes: list[tuple[str, str]] = []
    svc = _jstr(flow.get("service")).strip()
    api = flow.get("api")
    ui_raw = flow.get("ui")

    if svc:
        nodes.append((svc, "svc"))
    if api is not None and _jstr(api):
        nodes.append((_jstr(api), "api"))
    if ui_raw is not None:
        uis = _jlist(ui_raw) if isinstance(ui_raw, list) else [_jstr(ui_raw)]
        for u in uis or []:
            if _jstr(u):
                nodes.append((_jstr(u), "ui-box"))

    return nodes


def generate_svg(data: dict[str, Any]) -> str:
    batch, live = parse_flows(data)
    out: list[str] = []

    def ln(s: str) -> None:
        out.append(s)

    header_h = 70
    section_gap = 24
    batch_h = SECTION_HDR + len(batch) * ROW_H if batch else 0
    live_h = SECTION_HDR + len(live) * ROW_H if live else 0
    content_h = batch_h + section_gap + live_h + 40
    svg_h = header_h + content_h

    ln(f'<svg xmlns="http://www.w3.org/2000/svg" width="{SVG_W}" height="{svg_h}" viewBox="0 0 {SVG_W} {svg_h}">')
    ln("  <defs>")
    ln('    <marker id="arrowhead" markerWidth="10" markerHeight="7" refX="9" refY="3.5" orient="auto">')
    ln('      <polygon points="0 0, 10 3.5, 0 7" fill="#94a3b8" />')
    ln("    </marker>")
    ln("    <style>")
    ln(CSS)
    ln("    </style>")
    ln("  </defs>")
    ln(f'  <rect class="bg" x="0" y="0" width="{SVG_W}" height="{svg_h}" />')

    ln('  <text x="40" y="32" class="title">Data Flow: Service → API → UI</text>')
    ln(
        '  <text x="40" y="50" class="subtitle">'
        "SSOT: data-flow-manifest.json. Batch (GCS) and Live (Pub/Sub). "
        "Generated by scripts/manifest/generate_data_flow_dag.py</text>"
    )
    ln('  <text x="40" y="64" class="subtitle">Domain data flows from services via APIs (or direct) to UIs.</text>')

    y = header_h
    margin = 50
    max_chain_w = SVG_W - 2 * margin

    def render_section(flows: list[dict[str, Any]], mode: str, mode_color: str) -> None:
        nonlocal y
        sect_w = SVG_W - 2 * margin
        ln(
            f'  <rect x="{margin}" y="{y}" width="{sect_w}"'
            f' height="{SECTION_HDR}" fill="#f8fafc" stroke="#e2e8f0" rx="6" />'
        )
        ln(f'  <text x="{margin + 12}" y="{y + 22}" class="section">{mode.upper()} flows</text>')
        y += SECTION_HDR

        for flow in flows:
            nodes = flow_nodes(flow)
            if not nodes:
                continue

            total_w = sum(box_width(n[0]) for n in nodes) + (len(nodes) - 1) * (ARROW_W + BOX_PAD)
            x_start = margin + (max_chain_w - total_w) // 2 if total_w < max_chain_w else margin
            cx = x_start

            for i, (name, cls) in enumerate(nodes):
                w = box_width(name)
                ln(f'  <rect x="{cx}" y="{y}" width="{w}" height="{BOX_H}" class="{cls}" />')
                ln(
                    f'  <text x="{cx + w // 2}" y="{y + 22}"'
                    f' text-anchor="middle" class="label">{html_escape(name)}</text>'
                )
                cx += w
                if i < len(nodes) - 1:
                    ax1, ax2 = cx, cx + ARROW_W
                    ln(f'  <line x1="{ax1}" y1="{y + BOX_H // 2}" x2="{ax2}" y2="{y + BOX_H // 2}" class="arrow" />')
                    cx = ax2 + BOX_PAD

            y += ROW_H

    if batch:
        render_section(batch, "Batch", "#0ea5e9")
        y += section_gap
    if live:
        render_section(live, "Live", "#22c55e")

    ln("</svg>")
    return "\n".join(out) + "\n"


def generate(
    manifest_path: Path | None = None,
    output_path: Path | None = None,
) -> Path:
    src = manifest_path or MANIFEST
    dst = output_path or OUTPUT

    with open(src) as f:
        data = cast(dict[str, Any], json.load(f))

    svg_content = generate_svg(data)
    ET.fromstring(svg_content)  # nosec B314
    dst.write_text(svg_content)
    print(f"Generated: {dst}")
    return dst


if __name__ == "__main__":
    generate()
