#!/usr/bin/env bash
# Epic: security_and_cross_cutting_master
# Lifecycle: permanent
# Delete-when: NA
#
# rollout-manifest-driven-setup.sh — Generate manifest-driven setup-workspace.sh for all non-UI repos
#
# For each non-UI repo in workspace-manifest.json:
#   1. Generates a thin-wrapper scripts/setup-workspace.sh (sets SERVICE_NAME, delegates to PM script)
#   2. Commits the file to the repo (skips if already up-to-date)
#
# Usage:
#   bash scripts/rollout-manifest-driven-setup.sh [--dry-run] [--repo <name>] [--skip-commit]
#
# Options:
#   --dry-run      Print what would be done, don't write or commit
#   --repo <name>  Only process this specific repo (skip all others)
#   --skip-commit  Write files but don't git commit
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PM_DIR="$(dirname "$SCRIPT_DIR")"
WORKSPACE_ROOT="$(dirname "$PM_DIR")"
MANIFEST_PATH="$PM_DIR/workspace-manifest.json"

DRY_RUN=false
SKIP_COMMIT=false
FILTER_REPO=""

for arg in "$@"; do
    case "$arg" in
        --dry-run)     DRY_RUN=true ;;
        --skip-commit) SKIP_COMMIT=true ;;
        --repo)        shift; FILTER_REPO="$1" ;;
    esac
done

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BLUE='\033[0;34m'; NC='\033[0m'
ok()   { echo -e "${GREEN}✅ $1${NC}"; }
warn() { echo -e "${YELLOW}⚠️  $1${NC}"; }
info() { echo -e "${BLUE}ℹ️  $1${NC}"; }

# Repos that get a setup-workspace.sh (non-UI Python repos)
get_target_repos() {
    python3 - "$MANIFEST_PATH" "$FILTER_REPO" <<'PYEOF'
import json, sys

manifest_path = sys.argv[1]
filter_repo   = sys.argv[2] if len(sys.argv) > 2 else ""

with open(manifest_path) as f:
    manifest = json.load(f)

repos = manifest.get("repositories", {})

# Skip UI repos and PM itself (no Python deps; UI handled separately)
SKIP_TYPES = {"ui"}
SKIP_NAMES = {"unified-trading-pm"}

for name, data in repos.items():
    if filter_repo and name != filter_repo:
        continue
    repo_type = data.get("type", "")
    if repo_type in SKIP_TYPES or name in SKIP_NAMES:
        continue
    print(name)
PYEOF
}

# Generate the thin-wrapper script content for a given repo
generate_wrapper() {
    local service_name="$1"
    cat <<WRAPPER
#!/usr/bin/env bash
#
# setup-workspace.sh — ${service_name}
#
# Auto-generated by unified-trading-pm/scripts/rollout-manifest-driven-setup.sh
# Do NOT edit directly. To regenerate:
#   bash unified-trading-pm/scripts/rollout-manifest-driven-setup.sh --repo ${service_name}
#
# Clones manifest dependencies as siblings, runs pre-flight checks, installs Python deps.
# Logic lives in unified-trading-pm/scripts/setup-workspace-from-manifest.sh (SSOT).
#
set -euo pipefail

SERVICE_NAME="${service_name}"

SCRIPT_DIR="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
SERVICE_DIR="\$(dirname "\$SCRIPT_DIR")"
WORKSPACE_ROOT="\${WORKSPACE_ROOT:-\$(dirname "\$SERVICE_DIR")}"
GH_ORG="\${GH_ORG:-IggyIkenna}"
GH_TOKEN="\${GH_TOKEN:-\${GITHUB_TOKEN:-}}"

# ── CLONE PM FIRST (contains manifest + shared bootstrap script) ───────────────
PM_DEST="\$WORKSPACE_ROOT/unified-trading-pm"
if [ ! -d "\$PM_DEST" ]; then
    echo "Cloning unified-trading-pm (manifest source)..."
    if [ -n "\$GH_TOKEN" ]; then
        git clone --depth=1 "https://x-access-token:\${GH_TOKEN}@github.com/\${GH_ORG}/unified-trading-pm.git" "\$PM_DEST"
    else
        git clone --depth=1 "https://github.com/\${GH_ORG}/unified-trading-pm.git" "\$PM_DEST"
    fi
fi

# ── DELEGATE TO MANIFEST-DRIVEN SCRIPT (SSOT in PM) ───────────────────────────
exec bash "\$PM_DEST/scripts/setup-workspace-from-manifest.sh" "\$SERVICE_NAME" "\$@"
WRAPPER
}

# ── CHECKSUM HELPER ───────────────────────────────────────────────────────────
file_checksum() {
    sha256sum "$1" 2>/dev/null | cut -d' ' -f1 || shasum -a 256 "$1" 2>/dev/null | cut -d' ' -f1 || echo ""
}

PASS=0; SKIP=0; FAIL=0
TARGET_REPOS=$(get_target_repos)
TOTAL=$(echo "$TARGET_REPOS" | wc -l | tr -d ' ')

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Rollout: manifest-driven setup-workspace.sh"
echo "  Repos:   $TOTAL targets"
echo "  DRY_RUN: $DRY_RUN | SKIP_COMMIT: $SKIP_COMMIT"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

while IFS= read -r repo; do
    [ -z "$repo" ] && continue

    repo_dir="$WORKSPACE_ROOT/$repo"
    if [ ! -d "$repo_dir" ]; then
        warn "$repo: directory not found at $repo_dir — skipping"
        SKIP=$((SKIP + 1))
        continue
    fi

    scripts_dir="$repo_dir/scripts"
    target_file="$scripts_dir/setup-workspace.sh"
    new_content=$(generate_wrapper "$repo")

    # Check if file already matches
    if [ -f "$target_file" ]; then
        existing_sum=$(file_checksum "$target_file")
        new_sum=$(echo "$new_content" | sha256sum 2>/dev/null | cut -d' ' -f1 \
                  || echo "$new_content" | shasum -a 256 2>/dev/null | cut -d' ' -f1 || echo "")
        if [ "$existing_sum" = "$new_sum" ]; then
            info "$repo: setup-workspace.sh already up-to-date"
            SKIP=$((SKIP + 1))
            continue
        fi
    fi

    if $DRY_RUN; then
        echo "DRY-RUN: would write $target_file"
        PASS=$((PASS + 1))
        continue
    fi

    # Write the file
    mkdir -p "$scripts_dir"
    echo "$new_content" > "$target_file"
    chmod +x "$target_file"
    ok "$repo: wrote $target_file"

    if $SKIP_COMMIT; then
        PASS=$((PASS + 1))
        continue
    fi

    # Commit
    (
        cd "$repo_dir"
        git add "scripts/setup-workspace.sh"
        if git diff --cached --quiet; then
            info "$repo: no staged changes after write (identical content)"
        else
            git commit -m "chore: manifest-driven setup-workspace.sh (auto-generated)

Thin wrapper delegates to unified-trading-pm/scripts/setup-workspace-from-manifest.sh.
Reads workspace-manifest.json to clone exact deps for this service as GHA siblings.
Adds pre-flight checks: required dep clone failures = exit 1; version constraint warn.

Auto-generated by scripts/rollout-manifest-driven-setup.sh"
            ok "$repo: committed"
        fi
    ) && PASS=$((PASS + 1)) || { warn "$repo: commit failed"; FAIL=$((FAIL + 1)); }

done <<< "$TARGET_REPOS"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Rollout complete"
echo "  ✅ Updated: $PASS  |  ⏭  Skipped: $SKIP  |  ❌ Failed: $FAIL"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

[ "$FAIL" -eq 0 ] || exit 1
