# Epic: security_and_cross_cutting_master
# Lifecycle: permanent
# Delete-when: NA
"""generate_coverage_targets_local.py — bootstrap per-repo coverage_targets_local.yaml.

Phase 8.A P0 of deployment_and_qg_strategy_implementation_2026_05_13.

For each repo in workspace-manifest.json, walks coverage_targets.yaml + checks
which surfaces have at least one file matching the surface's glob_patterns
inside that repo. Writes <repo>/scripts/quality_gates/coverage_targets_local.yaml
with the enabled-surfaces subset. "default" is always enabled.

Idempotent: refuses to overwrite an existing file unless --force.

Usage:
    python3 unified-trading-pm/scripts/quality_gates/generate_coverage_targets_local.py
    python3 unified-trading-pm/scripts/quality_gates/generate_coverage_targets_local.py --force
    python3 unified-trading-pm/scripts/quality_gates/generate_coverage_targets_local.py --dry-run
    python3 unified-trading-pm/scripts/quality_gates/generate_coverage_targets_local.py --repo execution-service
"""

from __future__ import annotations

import argparse
import fnmatch
import json
import sys
from pathlib import Path
from typing import cast

import yaml

SCRIPT_DIR = Path(__file__).resolve().parent
WORKSPACE_ROOT = SCRIPT_DIR.parent.parent.parent
TARGETS_PATH = SCRIPT_DIR / "coverage_targets.yaml"
MANIFEST_PATH = WORKSPACE_ROOT / "unified-trading-pm" / "workspace-manifest.json"


def _load_surfaces() -> dict[str, list[str]]:
    """Returns {surface_name: [glob_patterns]}."""
    loaded = cast(object, yaml.safe_load(TARGETS_PATH.read_text(encoding="utf-8")))
    if not isinstance(loaded, dict):
        return {}
    surfaces = cast(dict[str, object], loaded).get("surfaces")
    if not isinstance(surfaces, dict):
        return {}
    out: dict[str, list[str]] = {}
    for name, body in cast(dict[str, object], surfaces).items():
        if not isinstance(body, dict):
            continue
        patterns = cast(dict[str, object], body).get("glob_patterns")
        if isinstance(patterns, list):
            out[name] = [str(p) for p in cast(list[object], patterns)]
    return out


def _load_repos() -> list[str]:
    loaded = cast(object, json.loads(MANIFEST_PATH.read_text(encoding="utf-8")))
    if not isinstance(loaded, dict):
        return []
    repos = cast(dict[str, object], loaded).get("repositories")
    if isinstance(repos, dict):
        return sorted(repos.keys())
    if isinstance(repos, list):
        return sorted(str(r) for r in cast(list[object], repos))
    return []


def _walk_repo_python_files(repo_path: Path) -> list[str]:
    """Return workspace-root-relative paths of .py + .sh files in the repo, excluding venv/build."""
    out: list[str] = []
    for f in repo_path.rglob("*"):
        if not f.is_file():
            continue
        if f.suffix not in (".py", ".sh"):
            continue
        parts = f.relative_to(repo_path).parts
        if any(
            skip in parts
            for skip in (
                ".venv",
                "venv",
                "build",
                "dist",
                "node_modules",
                "__pycache__",
                ".git",
                ".pytest_cache",
                ".mypy_cache",
                ".ruff_cache",
            )
        ):
            continue
        out.append(f"{repo_path.name}/{f.relative_to(repo_path).as_posix()}")
    return out


def _surface_matches_repo(surface_patterns: list[str], repo_files: list[str]) -> bool:
    for pat in surface_patterns:
        for f in repo_files:
            if fnmatch.fnmatch(f, pat):
                return True
    return False


def _write_local_yaml(repo_path: Path, surfaces: list[str], dry_run: bool, force: bool) -> str:
    target = repo_path / "scripts" / "quality_gates" / "coverage_targets_local.yaml"
    target.parent.mkdir(parents=True, exist_ok=True)
    if target.exists() and not force:
        return f"SKIP {repo_path.name}: {target.relative_to(WORKSPACE_ROOT)} already exists (use --force)"

    content = (
        "# Per-repo coverage-target enablement — Phase 8.A of\n"
        "# deployment_and_qg_strategy_implementation_2026_05_13.\n"
        "#\n"
        "# Generated by unified-trading-pm/scripts/quality_gates/generate_coverage_targets_local.py.\n"
        "# Lists which workspace surfaces (from coverage_targets.yaml) apply to THIS repo.\n"
        "# `default` is always enabled; remove or add surfaces to tune what this repo's QG enforces.\n"
        "\n"
        "enabled_surfaces:\n"
    )
    for s in surfaces:
        content += f"  - {s}\n"

    if dry_run:
        return f"DRY  {repo_path.name}: would write {len(surfaces)} surfaces: {', '.join(surfaces)}"

    target.write_text(content, encoding="utf-8")
    return f"OK   {repo_path.name}: wrote {len(surfaces)} surfaces → {target.relative_to(WORKSPACE_ROOT)}"


def main() -> int:
    parser = argparse.ArgumentParser(description="Bootstrap per-repo coverage_targets_local.yaml")
    parser.add_argument("--repo", default="all", help="Single repo OR 'all'")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--force", action="store_true", help="Overwrite existing file")
    ns = parser.parse_args()

    repo_filter: str = cast(str, ns.repo)
    dry_run: bool = cast(bool, ns.dry_run)
    force: bool = cast(bool, ns.force)

    surfaces = _load_surfaces()
    if not surfaces:
        print(f"ERROR: no surfaces loaded from {TARGETS_PATH}", file=sys.stderr)
        return 2

    target_repos = [repo_filter] if repo_filter != "all" else _load_repos()
    if not target_repos:
        print("ERROR: no repos found", file=sys.stderr)
        return 2

    skip_repos = {
        "unified-trading-pm",
        "unified-trading-system-ui",
        "deployment-ui",
        "e2e-testing",
        "system-integration-tests",
        "ibkr-gateway-infra",
    }

    for repo_name in target_repos:
        if repo_name in skip_repos:
            print(f"SKIP {repo_name}: not python-service (no coverage.xml expected)")
            continue
        repo_path = WORKSPACE_ROOT / repo_name
        if not repo_path.is_dir():
            print(f"SKIP {repo_name}: not on disk at {repo_path}")
            continue

        repo_files = _walk_repo_python_files(repo_path)
        enabled: list[str] = ["default"]
        for surface_name, patterns in surfaces.items():
            if surface_name == "default":
                continue
            if _surface_matches_repo(patterns, repo_files):
                enabled.append(surface_name)

        result = _write_local_yaml(repo_path, enabled, dry_run, force)
        print(result)

    return 0


if __name__ == "__main__":
    sys.exit(main())
