#!/bin/bash
# pm-pull-ff.sh v2 — smart FF-pull for ubuntu-owned unified-trading-pm clone
# Behaviour:
#   - skip on untracked (?? entries)
#   - skip on genuine tracked-dirty (operator/agent WIP)
#   - auto-stash + drop the closed set of known auto-regenerated files
#     (workspace-manifest products that VM cron regenerates locally)
set -e
PM=/home/ubuntu/unified-trading-system-repos/unified-trading-pm
cd "$PM"
TS=$(date -u +%FT%TZ)

# Closed set of auto-regenerated tracked files safe to stash-then-drop.
# Add to this list only if the file is regenerated by an idempotent local cron
# (i.e. dropping a local edit is harmless because the next regen restores it).
AUTO_REGEN_RE='^(WORKSPACE_MANIFEST_DAG\.svg|workspace-manifest\.json)$'

DIRTY_TRACKED=$(sudo -u ubuntu git status --porcelain | grep -v '^?? ' || true)
STASHED=0
if [ -n "$DIRTY_TRACKED" ]; then
  GENUINE=""
  REGEN=""
  while IFS= read -r line; do
    [ -z "$line" ] && continue
    f=$(echo "$line" | awk '{print $NF}')
    if echo "$f" | grep -qE "$AUTO_REGEN_RE"; then
      REGEN="$REGEN $f"
    else
      GENUINE="${GENUINE}${line}
"
    fi
  done <<< "$DIRTY_TRACKED"

  if [ -n "$GENUINE" ]; then
    echo "$TS pm-pull: skip (genuine tracked-dirty)"
    printf '%s' "$GENUINE" | head -10
    exit 0
  fi

  if [ -n "$REGEN" ]; then
    sudo -u ubuntu git stash push -q -m "pm-pull-auto-regen-$TS" -- $REGEN 2>&1 || {
      echo "$TS pm-pull: stash failed; aborting"; exit 1; }
    STASHED=1
    echo "$TS pm-pull: stashed auto-regen:$REGEN"
  fi
fi

sudo -u ubuntu git fetch --quiet origin live-defi-rollout 2>&1 || { echo "$TS pm-pull: fetch failed"; exit 1; }
BEFORE=$(sudo -u ubuntu git rev-parse HEAD)
if sudo -u ubuntu git merge --ff-only --quiet origin/live-defi-rollout 2>&1; then
  AFTER=$(sudo -u ubuntu git rev-parse HEAD)
  if [ "$BEFORE" != "$AFTER" ]; then
    echo "$TS pm-pull: advanced $(echo $BEFORE | cut -c1-8) -> $(echo $AFTER | cut -c1-8)"
    # Re-assert per-root agent symlinks (top-level CLAUDE.md + skills) after the FF, so the freshly
    # pulled ruleset is the one Claude Code auto-loads. Repo helper (auto-updates via pull); run as
    # ubuntu so symlinks are ubuntu-owned; best-effort (always exits 0) — never fails the pull.
    REGEN="$PM/scripts/dev/regen-agent-symlinks.sh"
    [ -f "$REGEN" ] && sudo -u ubuntu bash "$REGEN" 2>&1 | sed "s/^/$TS pm-pull: /" || true
  fi
else
  echo "$TS pm-pull: non-FF — manual merge required"
  # if we stashed, pop it back so we don't lose visibility of the dirty state
  [ "$STASHED" = "1" ] && sudo -u ubuntu git stash pop -q 2>&1 || true
  exit 1
fi

# Drop the auto-regen stash — these files will be re-emitted by the local cron
if [ "$STASHED" = "1" ]; then
  if sudo -u ubuntu git stash list | head -1 | grep -q "pm-pull-auto-regen-$TS"; then
    sudo -u ubuntu git stash drop -q
    echo "$TS pm-pull: dropped auto-regen stash"
  fi
fi
