#!/bin/bash
# Epic: security_and_cross_cutting_master
# Lifecycle: permanent
# Delete-when: NA
# pm-pull-ff.sh v2 — smart FF-pull for ubuntu-owned unified-trading-pm clone
# Behaviour:
#   - skip on untracked (?? entries)
#   - skip on genuine tracked-dirty (operator/agent WIP)
#   - auto-stash + drop the closed set of known auto-regenerated files
#     (workspace-manifest products that VM cron regenerates locally)
#
# Dirty-drift Slack alerting (operator direction 2026-08-10): ported from
# ao-self-pull.sh's proven wedge-alert pattern. Before this, a genuine
# tracked-dirty skip had NO escalation path at all — this root/main PM clone
# sat 139 commits behind origin for 2+ hours (pm-pull.timer fires every 5 min
# — OnUnitActiveSec=300 — so that's ~24+ silent skips), discovered only by
# chance. Alerts on the same two signals ao-self-pull.sh tracks: (a) stuck
# dirty for PM_DIRTY_ALERT_TICKS (default 12, ~1h at this timer's 5-min
# cadence) consecutive ticks, and (b) drifted >= PM_DRIFT_ALERT_COMMITS
# (default 10) commits behind origin while dirty. Tagged "Root Main Clone" —
# this script always targets the single root PM clone installed by
# install_pm_pull.sh (never a slot), unlike slot-cron-ff-pull.sh's per-slot tag.
# Webhook read from agent-orchestrator's .env.local (this clone has none of
# its own) — the one already-provisioned webhook this host uses for every
# other cron-alert path.
set -e
PM=/home/ubuntu/unified-trading-system-repos/unified-trading-pm
AO_DIR=/home/ubuntu/unified-trading-system-repos/agent-orchestrator
cd "$PM"
TS=$(date -u +%FT%TZ)

# Shared Slack-post + dedup, mirrors ao-self-pull.sh's _post_wedge_slack_alert.
_post_pm_wedge_slack_alert() {
  reason="$1"; statefile="$2"
  now=$(date +%s)
  last=$(cat "$statefile" 2>/dev/null || echo 0)
  if [ $(( now - last )) -lt "${PM_WEDGE_ALERT_INTERVAL:-14400}" ]; then return 0; fi
  webhook=$(sed -n 's/^AGENT_ORCHESTRATOR_SLACK_WEBHOOK=//p' "$AO_DIR/.env.local" 2>/dev/null | head -1)
  if [ -z "$webhook" ]; then echo "$TS pm-pull: WEDGE ($reason) — no webhook"; return 0; fi
  echo "$now" > "$statefile" 2>/dev/null || true
  msg=":rotating_light: pm-pull-ff WEDGED on Root Main Clone ($PM): $reason — this checkout is silently drifting from LDR. Resolve in $PM."
  curl -s -m 10 -X POST -H 'Content-type: application/json' --data "{\"text\":\"$msg\"}" "$webhook" >/dev/null 2>&1 || true
  echo "$TS pm-pull: WEDGE alert fired ($reason)"
}

# Drift-behind alert: same predicate as ao-self-pull.sh's _alert_wedge.
_alert_pm_drift() {
  reason="$1"
  sudo -u ubuntu git fetch --quiet origin live-defi-rollout 2>/dev/null || true
  behind=$(sudo -u ubuntu git rev-list --count HEAD..origin/live-defi-rollout 2>/dev/null || echo 0)
  if [ "$behind" -lt "${PM_DRIFT_ALERT_COMMITS:-10}" ]; then return 0; fi
  _post_pm_wedge_slack_alert "Root Main Clone is $behind commits behind live-defi-rollout ($reason)" "${PM_WEDGE_STATE:-/tmp/pm-pull-wedge.alerted}"
}

# Consecutive-dirty-tick tracker, mirrors ao-self-pull.sh's _track_dirty_tick.
_DIRTY_TICKS_STATE="${PM_DIRTY_TICKS_STATE:-/tmp/pm-pull-dirty.ticks}"
_clear_pm_dirty_ticks() { rm -f "$_DIRTY_TICKS_STATE" 2>/dev/null || true; }
_track_pm_dirty_tick() {
  ticks=$(cat "$_DIRTY_TICKS_STATE" 2>/dev/null || echo 0)
  case "$ticks" in ''|*[!0-9]*) ticks=0 ;; esac
  ticks=$(( ticks + 1 ))
  echo "$ticks" > "$_DIRTY_TICKS_STATE" 2>/dev/null || true
  if [ "$ticks" -ge "${PM_DIRTY_ALERT_TICKS:-12}" ]; then
    _post_pm_wedge_slack_alert "Root Main Clone stuck dirty (non-churn) for $ticks consecutive ticks — deploy-currency silently frozen" "${PM_DIRTY_WEDGE_STATE:-/tmp/pm-pull-dirty-wedge.alerted}"
  fi
}

# Closed set of auto-regenerated tracked files safe to stash-then-drop.
# Add to this list only if the file is regenerated by an idempotent local cron
# (i.e. dropping a local edit is harmless because the next regen restores it).
AUTO_REGEN_RE='^(WORKSPACE_MANIFEST_DAG\.svg|workspace-manifest\.json)$'

DIRTY_TRACKED=$(sudo -u ubuntu git status --porcelain | grep -v '^?? ' || true)
STASHED=0
if [ -n "$DIRTY_TRACKED" ]; then
  GENUINE=""
  REGEN=""
  while IFS= read -r line; do
    [ -z "$line" ] && continue
    f=$(echo "$line" | awk '{print $NF}')
    if echo "$f" | grep -qE "$AUTO_REGEN_RE"; then
      REGEN="$REGEN $f"
    else
      GENUINE="${GENUINE}${line}
"
    fi
  done <<< "$DIRTY_TRACKED"

  if [ -n "$GENUINE" ]; then
    echo "$TS pm-pull: skip (genuine tracked-dirty)"
    printf '%s' "$GENUINE" | head -10
    _alert_pm_drift "dirty tree"
    _track_pm_dirty_tick
    exit 0
  fi

  if [ -n "$REGEN" ]; then
    sudo -u ubuntu git stash push -q -m "pm-pull-auto-regen-$TS" -- $REGEN 2>&1 || {
      echo "$TS pm-pull: stash failed; aborting"; exit 1; }
    STASHED=1
    echo "$TS pm-pull: stashed auto-regen:$REGEN"
  fi
fi
_clear_pm_dirty_ticks

sudo -u ubuntu git fetch --quiet origin live-defi-rollout 2>&1 || { echo "$TS pm-pull: fetch failed"; exit 1; }
BEFORE=$(sudo -u ubuntu git rev-parse HEAD)
if sudo -u ubuntu git merge --ff-only --quiet origin/live-defi-rollout 2>&1; then
  AFTER=$(sudo -u ubuntu git rev-parse HEAD)
  if [ "$BEFORE" != "$AFTER" ]; then
    echo "$TS pm-pull: advanced $(echo $BEFORE | cut -c1-8) -> $(echo $AFTER | cut -c1-8)"
    # Re-assert per-root agent symlinks (top-level CLAUDE.md + skills) after the FF, so the freshly
    # pulled ruleset is the one Claude Code auto-loads. Repo helper (auto-updates via pull); run as
    # ubuntu so symlinks are ubuntu-owned; best-effort (always exits 0) — never fails the pull.
    REGEN="$PM/scripts/dev/regen-agent-symlinks.sh"
    [ -f "$REGEN" ] && sudo -u ubuntu bash "$REGEN" 2>&1 | sed "s/^/$TS pm-pull: /" || true
  fi
else
  echo "$TS pm-pull: non-FF — manual merge required"
  # if we stashed, pop it back so we don't lose visibility of the dirty state
  [ "$STASHED" = "1" ] && sudo -u ubuntu git stash pop -q 2>&1 || true
  exit 1
fi

# Drop the auto-regen stash — these files will be re-emitted by the local cron
if [ "$STASHED" = "1" ]; then
  if sudo -u ubuntu git stash list | head -1 | grep -q "pm-pull-auto-regen-$TS"; then
    sudo -u ubuntu git stash drop -q
    echo "$TS pm-pull: dropped auto-regen stash"
  fi
fi
